
spring:
  application:
    name: eureka-client


management:
    endpoints:
        web:
            exposure:
                include: *


server:
  port: 8020

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 5
  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5




country:
  client: country-client
